import { ControlRoom, Evidence, FinalCTA, Footer, Nav, PageShell, Proof, Reveal, Simulation, VerticalFlow } from '../components/Site'
import { links } from '../data/content'

export default function OptionTwo() { return <PageShell className="option option-two"><div className="control-shell"><Nav enterprise dark /><main id="main">
  <section className="command-hero"><div className="container"><div className="command-kicker"><span>Enterprise AI readiness / operational view</span><strong>Live system · Sample interface</strong></div><Reveal className="command-title"><div><p className="eyebrow">AI risk management</p><h1>Turn AI use into an operating signal.</h1></div><div><p>Your team runs 15-minute simulations of real work. Leadership sees where judgment holds up, where risk appears, and what each person needs next.</p><a className="button" href={links.demo}>Schedule a briefing</a></div></Reveal><ControlRoom /></div></section>
  <section className="control-evidence"><div className="container"><Evidence dark /></div></section>
 </main></div><main>
  <section className="enterprise-brief section"><div className="container enterprise-brief-grid"><Reveal><p className="eyebrow">The exposure</p><h2>AI adoption is already happening. Governance needs evidence.</h2></Reveal><div><p className="lead">Prompting is the part everyone teaches. The harder part is choosing what to hand over and judging what comes back. That's what Itera measures.</p><ul><li>Individual and team readiness in real time.</li><li>Risk events with cited evidence.</li><li>Targeted practice and completion tracking.</li></ul></div></div></section>
  <section id="how" className="operations section"><div className="container"><div className="operations-head"><div><p className="eyebrow">Operational pipeline</p><h2>Nine stages. One accountable loop.</h2></div><p>Each stage converts observed work into the next usable artifact, from company context to measurable AI adoption.</p></div><VerticalFlow /></div></section>
  <section id="product" className="enterprise-input section"><div className="container split"><Simulation /><div><p className="eyebrow">Assessment input</p><h2>Simulate real work.</h2><p className="lead">“The email your manager asked for”, “urgent incident”, “price objection”. Your team makes the calls with AI in the flows they already own.</p><a className="text-link" href={links.cases}>Review the cases →</a></div></div></section>
  <section id="managers" className="enterprise-output section"><div className="container"><div className="output-head"><p className="eyebrow">Procurement-ready evidence</p><h2>Evidence leadership can inspect and defend.</h2></div><Proof /><p className="citation">Organizations with high shadow-AI use averaged $670K more in breach costs — IBM, Cost of a Data Breach Report 2025.</p></div></section>
  <FinalCTA enterprise />
 </main><Footer /></PageShell> }
